version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: my_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://my_user:my_password@postgres:5432/my_database
      NODE_ENV: production
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "start"]

volumes:
  postgres_data:
